config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/inner1'
  get 'home/inner2'

  get 'home/inner3'

  get 'home/inner4'
  
  
  root 'autentication#login'
  post 'autentication/usercreate'
  get 'home/cart'
  get 'autentication/index'
  
  get 'autentication/logout'
  post 'autentication/create'
  get 'home/cart'
  post 'home/innercreate1'
  post 'home/innercreate2'
  post 'home/innercreate3'
  post 'home/innercreate4'
  get 'home/productdele/:id' => 'home#productdele', as: 'home_productdele'
  

    

end

app/models/cart.rb
class Cart < ActiveRecord::Base
 	validates :quantity, presence: true
 	


end

app/models/user.rb
class User < ActiveRecord::Base
	require 'bcrypt'
	include BCrypt
	validates :email, presence: true
	validates :password, presence: true
	
  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  	
    @current_user = User.find(session[:current_user_id]) if session[:current_user_id]
  end 
  helper_method :current_user
end

app/controllers/autentication_controller.rb
class AutenticationController < ApplicationController
	layout 'home'
  before_action :pass_check, only: :usercreate
  before_action :email_exist, only: :usercreate
  	
 

  def usercreate

  	@member=User.new(req_params)
  	@member.password= params[:password]
   	if @member.save
   		flash[:notice]="Your registration is completed please login here"
   		redirect_to root_path

    else
       redirect_to autentication_index_path
    end
  	

  end

  def login


  end
  def create
    @member=User.find_by_email(params[:email])
    
    unless @member.nil?

      if @member.password == params[:password]
          session[:current_user_id]=@member.id
          redirect_to :controller => :home, :action => :index
      else
          flash[:error]="Your login is failed please enter correct password"
          redirect_to root_path
      end
    else
         flash[:error]="Your login is failed please enter correct email"
          redirect_to root_path

    end
  end
  def logout
    session[:current_user_id] =nil
    redirect_to root_path
  end

  private

  def req_params
   	params.permit(:firstname,:lastname,:email,:password,:address,:phonenumber)
  end

  def email_exist
    #binding.pry
    unless User.find_by_email(req_params['email']).nil?
      flash[:error] = 'Email already exists.You enter new email address'
      redirect_to autentication_index_path
    end
  end

  def pass_check
    unless params[:password] == params[:conformpassword]
      flash[:error] = "Password and confirmation password doesn't match"
      redirect_to autentication_index_path
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'
    before_action :current_user

		#========================cake===================
	def inner1
		@cart=Cart.new()
		 
	end
						#========================coffee===================
	def inner2
		@cart=Cart.new()
	end
	                 #========================tea===================
	def inner3
		@cart=Cart.new()
		
	end
	                 #=======================juice=======================
	def inner4
		@cart=Cart.new()	
	end

	def innercreate1
		
		count=params[:product].count-1
		

		(0..count).map {  |f| 

			@cart=Cart.new(:product => params[:product]["#{f}"],:quantity => params['quant']["#{f}"],:price => params['price']["#{f}"],:user_id => params[:user]["#{f}"])
			@cart.save

		} 
		
		
		redirect_to home_cart_path
		
	end

	def innercreate2
		
		count=params[:product].count-1
		

		(0..count).map {  |f| 

			@cart=Cart.new(:product => params[:product]["#{f}"],:quantity => params['quant']["#{f}"],:price => params['price']["#{f}"],:user_id => params[:user]["#{f}"])
			@cart.save

		} 
		
		
		redirect_to home_cart_path
		
	end


	def innercreate3
		
		count=params[:product].count-1
		

		(0..count).map {  |f| 

			@cart=Cart.new(:product => params[:product]["#{f}"],:quantity => params['quant']["#{f}"],:price => params['price']["#{f}"],:user_id => params[:user]["#{f}"])
			@cart.save

		} 
		
		
		redirect_to home_cart_path
		
	end
	def innercreate4
		
		count=params[:product].count-1
		

		(0..count).map {  |f| 

			@cart=Cart.new(:product => params[:product]["#{f}"],:quantity => params['quant']["#{f}"],:price => params['price']["#{f}"],:user_id => params[:user]["#{f}"])
			@cart.save

		} 
		
		
		redirect_to home_cart_path
		
	end

	def cart
		@cartitems=Cart.where('user_id = ?',current_user.id)
		@cartitemscount=Cart.where('user_id = ? and product != ?',current_user.id,'0').count

		
		
	end
	
	def inner

		 #@homes=Refineryhome.find_by_id(params[:id])
		 #@cart = Cart.new
		 #@homes = Refineryhome.all
	end

	def create
		# count=params[:product].count-1
		# (0..count).each do |f|
		# 	@cart=Cart.new(:product_id => params[:product]['f'],:quantity => params[:product]['f'],:price => params[:price],:user_id => params[:user_id])
		# 	@cart.save
		# end
		# @cart =  Cart.new(req_params)
		# if @cart.save
		# #redirect_to forum_topic_path(params[:refforum_id])
		# redirect_to home_cart_path
		
		
	end

	def productdele
		pdel=Cart.delete(params[:id])
		if pdel
			redirect_to home_cart_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/autentication/index.html.erb
<script language="javascript">

function checkEmail1() {

    var email = document.getElementById('txtEmail1');
    var name = document.getElementById('firstname').value;
    var name2 = document.getElementById('lastname').value;
    var password = document.getElementById('password').value;
    var password2 = document.getElementById('confirmpassword').value;
    var phonenumber = document.getElementById('phonenumber').value;
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
      
      if (name == "")
      {
        alert('Please provide first name');
       return false;
      }

      if (name2 == "")
      {
        alert('Please provide last name');
       return false;
      }

      if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
     }

      if (password == "")
      {
        alert('Please provide password');
       return false;
      }
       if (password2 == "")
      {
        alert('Please provide confirm password');
       return false;
      }
      if (phonenumber == "")
      {
        alert('Please provide phonenumber');
       return false;
      }

     
}</script>

 <div class="full_wrapper">
      <div class="site_container">
         <div class="product_full_wrap">
          <div class="signupinner">
            <h1>Signup</h1>
            <%= form_tag autentication_usercreate_path   do |f| %>
            <table cellpadding="0" cellspacing="0" class="formtable" width="100%">
                 <tbody>
                 <tr>
                    <td colspan="2" align="center" class="textsucess"> 
                      <% unless flash[:notice].nil? %>
                        <%= flash[:notice]  %>
                      <% end %>
                      <% unless flash[:error].nil? %>
                       <label style="color:red;"><%= flash[:error]  %></label> 
                      <% end %>
                   </td>
                 </tr>
                 <tr>
                     <td width="10%">First Name:</td>
                     <td width="90%"><%= text_field_tag 'firstname' , "", 
                     :id => 'firstname' %></td>
                 </tr>
                 <tr>
                     <td width="10%">Last Name:</td>
                     <td width="90%"><%= text_field_tag 'lastname' , "", :id => 'lastname' %></td>
                 </tr>
         
                 <tr>
                     <td>Email:</td>
                     <td><%= text_field_tag 'email',"", :id =>'txtEmail1' %></td>
                 </tr>
                 <tr>
                     <td>Password:</td>
                     <td><%= password_field_tag 'password',"", :id =>'password' %></td>
                 </tr>
                 <tr>
                     <td>Conform Password:</td>
                     <td><%= password_field_tag 'conformpassword',"", :id =>'confirmpassword' %></td>
                 </tr>
              <tr>
                     <td valign="top">Address:</td>
                     <td><%= text_area_tag 'address' %></td>
                 </tr>
                 <tr>
                     <td>Phone Number:</td>
                     <td><%= text_field_tag 'phonenumber' , "", :id =>'phonenumber'  %></td>
                 </tr>
                 
                 <tr>
                     <td></td>
                     <td>
                      <%= submit_tag "Submit", :onclick => 'Javascript:checkEmail1();' %>
                     </td>
                 </tr>

           </tbody></table>
           <% end -%>
          </div>
         </div><!--product_full_wrap-->
      
      <!-- <div class="product_right_wrap">
      
       <div class="merchant_wrap">
        
         <h3>Not A Merchant Yet?</h3>
         <p>Subscribe to get your business Featured on your Tameion, Inc./Clikarro.com Website.</p>
       
       </div><!--merchant_wrap-->

      <!--  <div class="merchant_wrap1">
        
         <h4>Compare Products</h4>
         <p>You have no Products</p> -->
       
      <!--  </div> --><!--merchant_wrap1-->
      
      <!-- <h3>Featured Merchants</h3>
      <div style="margin-top:10px;"> -->

      <%#= image_tag 'mexican_food_29.png'%><!-- </div>
       
      
      
      </div> --> 
     <div class="clear_fix"></div>
     
      </div>
     </div>
     
     <div class="clear_fix"></div>

app/views/autentication/login.html.erb
<div class="full_wrapper">
      <div class="site_container">
         <div class="product_full_wrap">
          <div class="signupinner">
            <h1>Login</h1>
            
          <%= form_tag autentication_create_path   do |f| %>
            <table cellpadding="0" cellspacing="0" class="formtable" width="100%">
                 <tbody>
                 <tr>
                   <td colspan="2" align="center" class="textsucess"> 
                      <% unless flash[:notice].nil? %>
                        <%= flash[:notice]  %>
                      <% end %>
                      <% unless flash[:error].nil? %>
                       <label style="color:red;"><%= flash[:error]  %></label> 
                      <% end %>
                   </td>
                 </tr>
                 <tr>
                     <td width="10%">Email:</td>
                     <td width="90%">
                      <%= text_field_tag 'email',"", :id => "txtEmail" %>
                     </td>
                 </tr>
                 <tr>
                     <td width="10%">Password:</td>
                     <td width="90%"><%= password_field_tag 'password',"", :id => "password" %></td>
                 </tr>
         
                

                 <tr>
                      <td></td>
                     <td colspan="2">
                       <%= submit_tag "Login", :onclick => 'Javascript:checkEmail();' %>
                       <label style="margin-left:15px;font-size:16px;">Are you new user? Click <%= link_to 'Register ', autentication_index_path  %>Here</label>
                     </td>
                     
                     
                 </tr>

           </tbody></table>
           <% end -%>
          </div>
         </div><!--product_full_wrap-->
      
      <!-- <div class="product_right_wrap">
      
       <div class="merchant_wrap">
        
         <h3>Not A Merchant Yet?</h3>
         <p>Subscribe to get your business Featured on your Tameion, Inc./Clikarro.com Website.</p>
       
       </div><!--merchant_wrap-->

      <!--  <div class="merchant_wrap1">
        
         <h4>Compare Products</h4>
         <p>You have no Products</p> -->
       
       <!-- </div> --><!--merchant_wrap1-->
      
     <!--  <h3>Featured Merchants</h3> -->
      <!-- <div style="margin-top:10px;"> -->

      <%#= image_tag 'mexican_food_29.png'%></div>
       
      
      
     <!--  </div> --> 
     <div class="clear_fix"></div>
     
      </div>
     </div>
     
     <div class="clear_fix"></div>

     <script language="javascript">

function checkEmail() {

    var email = document.getElementById('txtEmail');
    var password = document.getElementById('password').value;
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

     if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
     }
      if (password == "")
      {
        alert('Please provide password');
       return false;
      }
}</script>

app/views/home/cart.html.erb
<div class="site_container">
           <div class="shipping_table">
              <%#@homes.each do |f| %>
                
                <div class="cart_row">
                 <div class="cart_img">Product Name</div>
                 <div class="cart_name"></div>
                 <div class="cart_edit"></div>
                 <div class="cart_unitprice">Unit Price</div>
                 <div class="cart_qty">Qty</div>
                 <div class="cart_subtotal">Subtotal</div>
                 <div class="cart_delete"></div>
                 <div class="clear_fix"></div>
                 </div><!--cart_row-->
                 
              <% unless  @cartitems.empty? %>
                  <% @finaltotal=0 %> 
                  <% @cartitems.each do |f| %>
                     
                   <% if f.product!= "0" %>
                      
                     <div class="cart_img1">
                       <%= image_tag f.product, :style =>"width:50px;" %><br>
                     <a href="<%= home_productdele_path(f.id) %>"><span>Remove</span></a></div>
                     <div class="cart_name1"><br/></div>
                     <div class="cart_edit1"></div>
                     <div class="cart_unitprice1">$
                     <%= number_with_precision(f.price, precision: 2) %>
                     </div>

                     <div class="cart_qty1"><%= f.quantity %></div>
                     <div class="cart_subtotal1">
                      <% @finaltotal=@finaltotal+f.price*f.quantity  %>
                      $<%= number_with_precision(f.price*f.quantity, precision: 2) %>

                     </div>
                     <div class="clear_fix"></div>
                   <% end %>
                   <% end %>
              <% else %>
                   <div class="cart_img1">
                       <br>
                     <a href=""><span></span></a></div>
                     <div class="cart_name1"> No products selected...</div>
                     <div class="cart_edit1"></div>
                     <div class="cart_unitprice1"></div>
                     <div class="cart_qty1"></div>
                     <div class="cart_subtotal1"></div>
                     <div class="clear_fix"></div>
              <% end %>
                 
                 
                 <div class="cart_row1">
                
                 <div class="cont_shop_btn">
                     
                     <a href="<%= home_index_path %>" class="cont_shop">Continue Shopping</a>
                 </div><!--cont_shop_btn-->
                 
                 <div class="cont_shop_btn1">
                     <input type="submit" value="Clear Shopping Cart"> 
                     <input type="submit" value="Update Shopping Cart">
                 </div><!--cont_shop_btn1-->
                 
                 <div class="clear_fix"></div>
               
                 </div><!--cart_row-->


              </div><!--shipping_table-->

        <div class="cart_left">
               <h3>Estimated Shipping and Tax</h3>
               
               <p>Enter your destination to get a shipping estimate.</p>
               <div class="cart_text">Country<span class="red">*</span></div>
               <div class="cart_btn"><select><option>United States</option></select></div>
               <div class="cart_text">State/Province</div>
               <div class="cart_btn"><select><option>Please select state, region, Province</option></select></div>
               <div class="cart_text">Zip/Postal Code</div>
               <div class="cart_btn"><input type="text"></div>
               <div class="cart_btn"><input type="submit" value="Get a Quote"></div>
              </div><!--cart_left-->
              
              <div class="cart_right">
              
               <div class="cartinner_left">
                   
                   <h3>Discount Codes</h3>
                   <div class="cart_text">Enter Your Coupon Code if you have one.</div>
                   <div class="cartinner_btn"><input type="text"></div>
                   <div class="cartinner_btn"><input type="submit" value="Apply Coupon"></div>
               
               </div>
               
               
               <div class="cartinner_right">
                     <ul class="subtoatallis">
                      <li></li>
                     </ul>
                     <ul class="subtoatallis1">
                      <li><span>Final Total</span>
                        
                        <%= number_with_precision(@finaltotal, precision: 2) %>
                      </li>
                     </ul>
                     <a href="<%=home_index_path %>">
                      <input type="submit" value="Save in Cart" /></a>
                      <div class="clear_fix"></div>
                     <div class="proceedtochekoutimg">
                     <a href="#"> <img src="images/cart_03.png" alt=""></a>
                     </div>
                <div class="checkoutgay">
                      Checkout With Multiple Address
                     </div>     
               </div>
                     
               
              
              <div class="clear_fix"></div>
              <div class="clear_fix"></div>
  
              <%#end%>
            </div>
           </div>  
           <div class="clear_fix"></div>

app/views/home/inner1.html.erb
<script language="javascript">

function validateform() {

    alert();
    var quan = document.getElementById('quantity').value;
    var quan2 = document.getElementById('quantity2').value;
    var quan3 = document.getElementById('quantity3').value;
    var quan4 = document.getElementById('quantity4').value;

      if (quan== "")
      {
        alert('Please provide first name');
       return false;
      }
      if (quan2 == "")
      {
        alert('Please provide first name');
       return false;
      }
       if (quan3 == "")
      {
        alert('Please provide first name');
       return false;
      }
        if (quan4 == "")
      {
        alert('Please provide first name');
       return false;
      }
}</script>


<div class="full_wrapper">
      <div class="site_container">
         <%= form_tag home_innercreate1_path   do |f| %>
      <div class="betcam_wrap">
     <!--  <a href="<%#=home_index_path%>" class="active">Home</a> -->
      <!-- <span><%#= image_tag 'right_arrow_03.png'%></span>
      <a href="#">Group Deals</a>
      <span><%#= image_tag 'right_arrow_03.png'%></span>
      <a href="#">Chattanooga</a>
      <span><%#= image_tag 'right_arrow_03.png'%></span>
      <a href="#">Dannys Service Center zxfsz</a> </div> -->
      
      <div class="product_full_wrapper">
      
         <div class="product_inner_wrap">
            <h2>Dannys Service Center</h2>   

            <div class="product_inner_left">
            
              <div><%= image_tag 'main cake.jpg'%></div>
              <h3>Ingredients:</h3>
              <div >
              <ul class="product_lists" >
                
                <li>

                    <%= image_tag 'download (6).jpg', :style => 'height:100px' %><br>
                     <span>Add to cart:</span>
                    <%= check_box("product", "0", { },'download (6).jpg' ) %>
                    <br>
                    <span>Quantity:</span>
                  
                    <%= text_field_tag 'quant[0]','', :style => "width:22px;", 
                    :id => 'quantity'  %>
                    <span>Price:</span>
                    <%= text_field_tag 'price[0]','12',:readonly => true, :style => "width:22px;" %>
                    <%= hidden_field_tag 'user[0]',current_user.id %>
                </li>
                <li>
                    <%= image_tag 'download (5).jpg', :style => 'height:100px'%><br>
                    <span>Add to cart:</span>
                    <%= check_box("product", "1", { },'download (5).jpg' ) %>
                    <br>
                    <span>Quantity:</span>
                  
                    <%= text_field_tag 'quant[1]','', :style => "width:22px;" %>
                    <span>Price:</span>
                    <%= text_field_tag 'price[1]','12', :style => "width:22px;" %>
                    <%= hidden_field_tag 'user[1]',current_user.id %>
                </li>
                <li>
                    <%= image_tag 'download (3).jpg', :style => 'height:100px'%> <br>
                    <span>Add to cart:</span>
                    <%= check_box("product", "2", { },'download (3).jpg' ) %>
                    <br>
                    <span>Quantity:</span>
                  
                    <%= text_field_tag 'quant[2]','', :style => "width:22px;" %>
                    <span>Price:</span>
                    <%= text_field_tag 'price[2]','12',:readonly => true, :style => "width:22px;" %>
                    <%= hidden_field_tag 'user[2]',current_user.id %>

                </li>
                <li>
                    <%= image_tag 'download (2).jpg', :style => 'height:100px'%> <br>
                    <span>Add to cart:</span>
                    <%= check_box("product", "3", { },'download (2).jpg' ) %>
                    <br>
                    <span>Quantity:</span>
                  
                    <%= text_field_tag 'quant[3]','', :style => "width:22px;" %>
                    <span>Price:</span>
                    <%= text_field_tag 'price[3]','12',:readonly => true, :style => "width:22px;" %>
                    <%= hidden_field_tag 'user[3]',current_user.id %>
                </li>
                <li>
                    <%= image_tag 'download (4).jpg', :style => 'height:100px'%> <br>
                    <span>Add to cart:</span>
                    <%= check_box("product", "4", { },'download (4).jpg' ) %>
                    <br>
                    <span>Quantity:</span>
                  
                    <%= text_field_tag 'quant[4]','', :style => "width:22px;" %>
                    <span>Price:</span>
                    <%= text_field_tag 'price[4]','12', :readonly => true, :style => "width:22px;" %>
                    <%= hidden_field_tag 'user[4]',current_user.id %>
                </li>
              <div class="clear_fix"></div>
              </div>
              </ul>
            
            </div><!--product_inner_left-->

            <div class="product_inner_right">
            
                <ul class="service_list">
                
                  <li>
                   <!-- <p>NOW FROM</p> -->
                   
                   <!-- <div class="price_value">$<%#=@homes. price%> 30<span>$50</span></div> -->
                  <!--  <div class="price_discount">Extra $5 Off Ends 12/1</div> -->
                   <div><%= submit_tag 'Buy',:class => 'buy_wrap', :onclick => "return validateform()"%></div>
                   </li>
                   <!-- <div class="give_gift"><a href="#"><%#= image_tag 'service_center_10.png'%>GIVE AS A GIFT</a></div> -->
                   <%#= submit_tag 'Create an account'%>
                    
                   <!-- <ul class="pricevalue_list1">

                    <li>
                        <div style="font-weight:bold; color:#000;">Value</div>
                        <div style="font-weight:400; color:#000;">$36.00</div>
                     </li>   


                    <li>
                        <div style="font-weight:bold; color:#000;">Discount</div>
                        <div style="font-weight:400; color:#000;">60%</div>
                     </li>   


                    <li>
                        <div style="font-weight:bold; color:#000;">You Save</div>
                        <div style="font-weight:400; color:#000;">$36.00</div>
                     </li>   
                    <div class="clear_fix"></div>
                     
                   </ul> -->

                  </li>
                


                  <li>
                   <!-- <p>SALE STARTED AT</p> -->
                   <div class="sale_ending"><%= image_tag 'service_center_14.png'%> <%#= @homes.created_at.strftime("%m-%d-%Y") %></div>
                  
                  </li>

                  <li>
                   <p>LIMITED QUANTITY AVAILABLE</p>
                   <div class="quantity_limit"><%= image_tag 'service_center_17.png'%> Over 1,000 bought</div>
                    
                  
                  </li>



                  <li>
                   <p>SHARE THIS DEAL</p>
                   <div style="margin-top:10px;">
                   <a href="#"><%= image_tag 'service_center_31.png'%></a>
                   <a href="#"><%= image_tag 'service_center_33.png'%></a>
                   <a href="#"><%= image_tag 'service_center_35.png'%></a>
                   <a href="#"><%= image_tag 'service_center_37.png'%></a>
                   <a href="#"><%= image_tag 'fb_likes_40.png'%></a>
                   <a href="#"><%= image_tag 'fb_likes_42.png'%></a>
                   </div>
                  </li>
                
                </ul>
            
            </div><!--product_inner_right-->
            
            <div class="clear_fix"></div>
            
            <div style="border-top:1px dashed #bbbbbb; margin:10px 0px;"></div> 
            <h4>Description</h4>
            <p>Preheat oven to 350 degrees F (175 degrees C). Grease and flour a 9x9 inch pan or line a muffin pan with paper liners.
In a medium bowl, cream together the sugar and butter. Beat in the eggs, one at a time, then stir in the vanilla. Combine flour and baking powder, add to the creamed mixture and mix well. Finally stir in the milk until batter is smooth. Pour or spoon batter into the prepared pan.
Bake for 30 to 40 minutes in the preheated oven. For cupcakes, bake 20 to 25 minutes. Cake is done when it springs back to the touch.</p>
            
      
         
     

           
     
     
        </div><!--product_inner_wrap-->
      
      <!-- <div class="product_right_wrap">
      
       <div class="merchant_wrap">
        
         <h3>Not A Merchant Yet?</h3>
         <p>Subscribe to get your business Featured on your Tameion, Inc./Clikarro.com Website.</p>
       
       </div><!--merchant_wrap-->

      <!--  <div class="merchant_wrap1">
        
         <h4>Compare Products</h4>
         <p>You have no Products</p> -->
       
       <!-- </div> --><!--merchant_wrap1-->
      
      <!-- <h3>Featured Merchants</h3>
      <div style="margin-top:10px;"> -->

      <%#= image_tag 'mexican_food_29.png'%></div>
       
      
      
     <!--  </div>  --><!--product_right_wrap-->
      
     <div class="clear_fix"></div>
     
     </div><!--product_full_wrapper-->
     <%end%>
      </div>
     </div>


//     <script language="javascript">

//       function validateform()
//       alert(); 
//       {
//       var cake1 = document.getElementById('cake1').value;

//     if (cake1 == "")
//       {
//         alert('Please provide first name');
//        return false;
//       }

     
// }</script>

app/views/layouts/_header.html.erb
<header>
 <div class="site_container">

    <div class="heddr_logo">
    
       
    </div>
    
    <div class="heddr_right">

      <!-- <div class="contact_num"><b>Topics In Software Engineering Project</b></span></div> --><!--contact_num-->
    
      <div class="search_full_wrap">
      
           <div class="search_wrap"></div>
           <div class=""><%if current_user.nil? %>
           <h3> <%= 'Welcome Guest,' %></h3>
           <%else %>

          <h3> Welcome  <%=current_user.firstname %>,</h3>
          <%end %>
           </div>
           <div class="clear_fix"></div>
      
      </div><!--search_full_wrap-->

      <div class="clear_fix"></div>


         <ul class="menu_list">
              
              <li><a href="<%=home_cart_path %>"><%= image_tag 'social_icons_03.png'%>My Cart(<%= @cartitemscount %>)</a></li>
              <li><a href="#">Check out</a></li>
              <li><%if current_user.nil? %>

              <a href="<%= autentication_index_path %>">
              
              <%='Register' %></a>
              <%else %>
              <a href="<%=home_index_path %>">
              <%='My Profile' %></a>
              <%end %>

             </li>
              
              <% unless current_user.nil? %>
              <li><a href="<%= autentication_logout_path  %>">Logout</a></li>
              <% else %>
              <li><a href="<%= root_path%>">login</a></li>
              <% end %>
              
         </ul> 
              <div class="clear_fix"></div>
     
    
    </div><!--heddr_right-->


   <div class="clear_fix"></div>

 </div>
</header>

<div class="clear_fix"></div>   


   <!--  <nav>
        <div class="site_container">
        
          <ul class="nav_list">
          
            <li><a href="#" class="active">Shoppers Click Here</a></li>
            <li><a href="#">Sell Your Coupon</a></li>
            <li><a href="#">Merchant Validations</a></li>
          
          
          </ul>
        
        <div class="clear_fix"></div>
        
        
        </div>
    </nav>
     -->
<div class="clear_fix"></div>    



<div class="clear_fix"></div>

app/views/layouts/_slider.html.erb
<div class="full_wrapper">
 <div class="site_container">

 <div class="banner_part">

     <div class="banner_wrap">
     
          <div class="banner_content">
             <div style="font-size:18px; color:#fff;">Alaska cottage Suites</div>
             <div style="font-size:14px; color:#fff; margin-top:3px;">Kenai Peninsula suites | Homer, AK</div>
          </div><!--banner_content-->
          
          <div><%= image_tag 'home_banner_15.png'%></div>
     
     </div><!--banner_wrap-->    
     
     <div class="left_banner">
     
          <div class="left_banner_wrap">
              
               <div class="banner_content1">Green Organic</div>

               <div>
               <%= image_tag 'right_banners_17.png'%>


               </div>
              
          </div><!--left_banner_wrap-->
          
          <div class="left_banner_wrap1">
              
               <div class="banner_content2">Shaman Vegan Restaurant</div>
               <div>

                  <%= image_tag 'right_banners_20.png'%>

               </div>
              
          </div><!--left_banner_wrap1-->
    
     
     </div><!--left_banner-->
     
     <div class="clear_fix"></div>
     
     </div><!--banner_part-->
     
     
 </div>
</div>